version: "3.4"

services:
  magicmirror:
    image: magicmirror
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      DISPLAY: ":0"
    ports:
      - 8080:8080
