#!/usr/bin/env node
const fs = require("fs");
const path = require("path");

const configPath = path.resolve(__dirname, "../config/config.js");
const samplePath = path.resolve(__dirname, "../config/config.js.sample");
const configContent = fs.readFileSync(configPath, "utf8");
const newContent = configContent.replace(/appid: "(.*?)"/g, 'appid: "OPENWEATHER_API_KEY"');
fs.writeFileSync(samplePath, newContent);
